#!/usr/bin/env bash

# Use this function to get a owner from the array using the command inside an install script app_proxy_owner="$(_get_app_owner)"

declare -A app_owner

# #shellcheck source=sources/functions/app_owner
# . /etc/swizzin/sources/functions/app_owner
# _get_app_owner

#shellcheck source=sources/default_owners
. /etc/swizzin/sources/default_owners

_get_app_owner() {
    which_app="$(basename -- "$0" \.sh)"
    if [[ -n "${app_owner[${which_app}]+${which_app}}" ]]; then
        printf '%s' "${app_owner[${which_app}]}"
    else
        echo_error "ERROR get_app_owner ${which_app} does not exist or does not have a owner defined"
        exit 1
    fi
    return
}
